// <auto-generated />
namespace FinancialPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class check_user_householid_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(check_user_householid_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "201804062016098_check_user_householid_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
